openapi: 3.0.0

# before generation, change Repertoire: attribute in subject_genotype_response and all_subjects_genotype_response to repertoire_class, repertoire_class_list respectively
# to generate: datamodel-codegen  --input vdjbase-api-openapi3.yaml --input-file-type openapi --output new_model.py --output-model-type pydantic_v2.BaseModel --strict-nullable --use-subclass-enum
# after generation, change attributes back
# After generating model.py from the schema, please replace all occurrences of AwareDatetime with NaiveDatetime
# Also add an aliases as follows:
# class AllSamplesMetadataResponse(BaseModel):
#     repertoire_class_list: Optional[List[Repertoire]] = Field(
#       None,
#       description='List of Repertoire metadata for samples included in this dataset.',
#       alias='Repertoire'
#   )
# and
#class SampleMetadataResponse(BaseModel):
#    repertoire_class: Optional[Repertoire] = Field(
#        None, 
#        alias='Repertoire'
#    )

# this will switch the defined attribute from repertoire_class_list to Repertoire in the returned object
# the reason for these changes is that Pydantic does not allow attributes to have the same name as classes 


info:
  title: VDJbase API
  version: 1.0.0
  contact:
    name: William Lees
    email: william@lees.org.uk
  description: Public API for VDJbase holding AIRR-seq and Genomic data.
servers:
  - url: http://127.0.0.1:5000/api/v1
    description: VDJbase local development
    variables:
      basePath:
        default: api/v1
  - url: https://vdjbase.org/api/v1
    description: VDJbase production
    variables:
      basePath:
        default: api/v1
  - url: https://vdjbase.uat.vdjbase.org/api/v1
    description: VDJbase UAT
    variables:
      basePath:
        default: api/v1

components:
  schemas:
    # The response object for species lists
    species_response:
      type: object
      properties:
        species:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/Ontology'
        
    # The response object for datasets
    datasets_response:
      type: object
      properties:
        datasets:
          type: array
          items:
            type: object
            properties:
              dataset:
                type: string
                description: Name of the dataset in VDJbase
              revision_date:
                type: string
                format: date-time
                description: Date of the current revision of the dataset
              locus:
                type: string
                description: Gene locus it represents
                enum:
                    - IGH
                    - IGI
                    - IGK
                    - IGL
                    - TRA
                    - TRB
                    - TRG
                    - TRD
    
    # the response object for subjects and samples within a dataset
    subject_dataset_response:
          type: object
          properties:
            subject_datasets:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string        
                    description: The sample ID within VDJbase
                  study_name:
                    type: string        
                    description: The study name (MiAIRR study.study_id)
                  subject_identifier:  
                    type: string        
                    description: The subject ID as defined by the submitter of the study, unique within the study (MiAIRR subhect.subject_id)
                  sample_identifier:
                    type: string
                    description: Sample ID assigned by submitter, unique within study. (MiAIRR sample.sample_id)
                  dataset:
                    type: string
                    description: The VDJbase dataset
                    example: IGH
            
    # the response object for subject genotype
    subject_genotype_response:
      type: object
      properties:
        GenotypeSet: 
          $ref: './Repertoire.yaml#/GenotypeSet'

    # the response object for all subjects genotypes
    all_subjects_genotype_response:
      type: object
      properties:
        genotype_class_list: 
          description: List of Genotypes for all subjects included in this data type.
          type: array
          nullable: true
          items:
              type: object
              properties:
                subject_name: 
                  type: string
                  description: The VDJbase subject name
                genotypeSet:  
                  $ref: './Repertoire.yaml#/GenotypeSet'


    # the response object for sample metadata
    sample_metadata_response:
      type: object
      properties:
        Repertoire: 
          $ref: './Repertoire.yaml#/Repertoire'

    # the response object for all samples metadata
    all_samples_metadata_response:
      type: object
      properties:
        Repertoire:
            description: List of Repertoire metadata for samples included in this dataset.
            type: array
            nullable: true
            items:
              $ref: './Repertoire.yaml#/Repertoire'

    # error response
    error_response:
      type: object
      properties:
        message:
          type: string
          description: Detail about the error

# todo: add two additional routes for AKC:
# - list all datasets in VDJbase (together with species, locus and revision date)
# - provide metadata and genotypes for all samples included in a set of datasets (specify dataset as species, locus, dataset name)

paths:
  /{type}/species:
    get:
      summary: List species with datasets
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
      responses:
        '200':
          description: A list of the available species.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/species_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /{type}/datasets/{species}:
    get:
      summary: List datasets for a species
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string
            description: binomial name of species
      responses:
        '200':
          description: A list of the available datasets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/datasets_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /{type}/subjects/{species}/{dataset}:
    get:
      summary: List subjects and samples in a dataset
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string
            description: binomial name of species
        - name: dataset
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase dataset name
      responses:
        '200':
          description: A list of subjects and samples in the specified dataset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subject_dataset_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '400':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
  /{type}/subject_genotype/{species}/{subject}:
    get:
      summary: Return the genotype for the sample
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string
            description: binomial name of species
        - name: subject
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase subject name
      responses:
        '200':
          description: The requested genotype.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subject_genotype_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '400':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
  /{type}/all_subjects_genotype/{species}:
    get:
      summary: Return genotypes for all subjects of the specified species in the specified data type
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string
            description: binomial name of species
      responses:
        '200':
          description: A list of genotypes for the requested subjects.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subject_genotype_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'                
        '400':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
  /{type}/sample_metadata/{species}/{dataset}/{sample}:
    get:
      summary: Return the MiAIRR metadata for the sample
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string
            description: binomial name of species
        - name: dataset
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase dataset name
        - name: sample
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase sample name
      responses:
        '200':
          description: A list of subjects and samples in the specified dataset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sample_metadata_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '400':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
  /{type}/all_samples_metadata/{species}/{dataset}:
    get:
      summary: Return the MiAIRR metadata for all samples in the specified dataset
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string
            description: binomial name of species
        - name: dataset
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase dataset name
      responses:
        '200':
          description: A list of subjects and samples in the specified dataset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/all_samples_metadata_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
        '400':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
